# Generated by Django 4.2 on 2023-04-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_campagne', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(blank=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image_campagne', models.ImageField(blank=True, null=True, upload_to='image_campagne/')),
                ('campagne_etat', models.CharField(choices=[('En cours', 'En cours'), ('Terminée', 'Terminée'), ('En pause', 'En pause')], max_length=20)),
                ('maitre_du_jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
            },
        ),
    ]
