# Generated by Django 4.2 on 2023-04-05 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warhammer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='campagne_etat',
            field=models.CharField(choices=[('En pause', 'En pause'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], max_length=20),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('race', models.CharField(choices=[('Elfe', 'Elfe'), ('Halfeling', 'Halfeling'), ('Nain', 'Nain'), ('Humain', 'Humain')], max_length=50)),
                ('sexe', models.CharField(choices=[('Mâle', 'Mâle'), ('Femelle', 'Femelle')], max_length=50)),
                ('vocation', models.CharField(choices=[('Filou', 'Filou'), ('Forestier', 'Forestier'), ('Guerrier', 'Guerrier'), ('Erudit', 'Erudit')], max_length=50)),
                ('alignement', models.CharField(choices=[('Bon', 'Bon'), ('Mauvais', 'Mauvais'), ('Chaotique', 'Chaotique'), ('Neutre', 'Neutre'), ('Loyal', 'Loyal')], max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('taille', models.CharField(blank=True, max_length=50, null=True)),
                ('poids', models.PositiveIntegerField(blank=True, null=True)),
                ('cheveux', models.CharField(blank=True, max_length=50, null=True)),
                ('yeux', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_personnage', models.ImageField(blank=True, null=True, upload_to='photo_perso/')),
                ('point_destin', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('debouches', models.TextField(blank=True, null=True)),
                ('point_folie', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('langue', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('mort_tuer', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warhammer.campagne')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
