# Generated by Django 4.2 on 2023-04-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0003_encombrementpersonnage_alter_player_alignement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armecontact',
            name='note',
            field=models.TextField(blank=True, default='Aucune note', null=True),
        ),
        migrations.AlterField(
            model_name='armedistance',
            name='armer_tirer',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='armedistance',
            name='note',
            field=models.TextField(blank=True, default='Aucune note', null=True),
        ),
        migrations.AlterField(
            model_name='armure',
            name='note',
            field=models.TextField(blank=True, default='Aucune note', null=True),
        ),
        migrations.AlterField(
            model_name='bourse',
            name='autre',
            field=models.TextField(blank=True, default='A définir', null=True),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='campagne_etat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminée', 'Terminée'), ('En pause', 'En pause')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competence',
            name='niveau',
            field=models.CharField(blank=True, default='Initial', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionpersonnelle',
            name='Membre_famille',
            field=models.TextField(blank=True, default='A définir', null=True),
        ),
        migrations.AlterField(
            model_name='descriptionpersonnelle',
            name='description_perso',
            field=models.TextField(blank=True, default='A définir', null=True),
        ),
        migrations.AlterField(
            model_name='descriptionpersonnelle',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='A définir', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='descriptionpersonnelle',
            name='signe_distinctif',
            field=models.TextField(blank=True, default='A définir', null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='encombrement',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='note',
            field=models.TextField(blank=True, default='Aucune note', null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plancarriere',
            name='nom',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='alignement',
            field=models.CharField(choices=[('Loyal', 'Loyal'), ('Chaotique', 'Chaotique'), ('Mauvais', 'Mauvais'), ('Neutre', 'Neutre'), ('Bon', 'Bon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='debouches',
            field=models.TextField(blank=True, default='Ajouter débouchés', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='langue',
            field=models.CharField(blank=True, default='A définir', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='mort_tuer',
            field=models.TextField(blank=True, default='Ajouter morts tués', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='note',
            field=models.TextField(blank=True, default='Aucune note', null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='poids',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.CharField(choices=[('Nain', 'Nain'), ('Elfe', 'Elfe'), ('Halfeling', 'Halfeling'), ('Humain', 'Humain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='vocation',
            field=models.CharField(choices=[('Erudit', 'Erudit'), ('Filou', 'Filou'), ('Forestier', 'Forestier'), ('Guerrier', 'Guerrier')], max_length=50),
        ),
    ]
