# Generated by Django 4.2 on 2023-05-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhammer', '0005_alter_campagne_campagne_etat_alter_player_alignement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alignement',
            field=models.CharField(choices=[('Chaotique', 'Chaotique'), ('Bon', 'Bon'), ('Mauvais', 'Mauvais'), ('Neutre', 'Neutre'), ('Loyal', 'Loyal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='race',
            field=models.CharField(choices=[('Elfe', 'Elfe'), ('Halfeling', 'Halfeling'), ('Humain', 'Humain'), ('Nain', 'Nain')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='vocation',
            field=models.CharField(choices=[('Filou', 'Filou'), ('Guerrier', 'Guerrier'), ('Forestier', 'Forestier'), ('Erudit', 'Erudit')], max_length=50),
        ),
    ]
