# Generated by Django 4.2 on 2023-05-19 14:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneCthulhu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_de_jeu', models.CharField(choices=[('Aventure Pulp', 'Aventure Pulp'), ('Horreur Lovecraftienne', 'Horreur Lovecraftienne'), ('Investigation Occulte', 'Investigation Occulte')], max_length=50)),
                ('nom_de_campagne', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('image_campagne', models.ImageField(blank=True, null=True, upload_to='image_campagne/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('campagne_etat', models.CharField(choices=[('En pause', 'En pause'), ('En cours', 'En cours'), ('Terminée', 'Terminée')], max_length=20)),
                ('gardien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['campagne_etat'],
            },
        ),
        migrations.CreateModel(
            name='Investigateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('occupation', models.CharField(choices=[('Explorateur', 'Explorateur'), ('Dilettante', 'Dilettante'), ('Détective', 'Détective'), ('Militaire', 'Militaire'), ('Médecin', 'Médecin'), ('Homme de foi', 'Homme de foi'), ('Journaliste', 'Journaliste'), ('Artiste', 'Artiste'), ('Universitaire', 'Universitaire'), ('Baroudeur', 'Baroudeur')], max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sexe', models.CharField(choices=[('Femelle', 'Femelle'), ('Mâle', 'Mâle')], max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=50)),
                ('personnalite', models.CharField(choices=[('Tatillon', 'Tatillon'), ('Timide', 'Timide'), ('Obsessionnel', 'Obsessionnel'), ('Anxieux', 'Anxieux'), ('Flegmatique', 'Flegmatique'), ('Jovial', 'Jovial'), ('Sanguin', 'Sanguin'), ('Méfiant', 'Méfiant'), ('Taciturne', 'Taciturne'), ('Narcissique', 'Narcissique')], max_length=50)),
                ('photo_investigateur', models.ImageField(blank=True, null=True, upload_to='photo_perso/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('cercle_proche', models.CharField(max_length=50)),
                ('cercle_eloigner', models.CharField(max_length=50)),
                ('cercle_opposer', models.CharField(max_length=50)),
                ('cercle_ennemis', models.CharField(max_length=50)),
                ('etat_investigateur', models.CharField(choices=[('Fou', 'Fou'), ('En pause', 'En pause'), ('Avec Cthulhu', 'Avec Cthulhu'), ('Mort', 'Mort'), ('Actif', 'Actif')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('campagne_cthulhu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cthulhu.campagnecthulhu')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigateur',
                'verbose_name_plural': 'Investigateurs',
            },
        ),
        migrations.CreateModel(
            name='CompetenceInvestigateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Sensorielle', 'Sensorielle'), ('Influence', 'Influence'), ('Action', 'Action'), ('Connaissance', 'Connaissance'), ('Savoir-faire', 'Savoir-faire')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('niveau_naturel', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('point_ajouter', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('tirage_xp', models.BooleanField(default=False)),
                ('is_occupation', models.BooleanField(default=False)),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Competence Investigateur',
                'verbose_name_plural': 'Competences Investigateurs',
            },
        ),
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('constitution', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('dexterite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('force', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('taille', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('education', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('pouvoir', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('aplomb', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Caracteristique',
                'verbose_name_plural': 'Caracteristiques',
            },
        ),
        migrations.CreateModel(
            name='Armes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Armes à Feu', 'Arme à Feu'), ('Armes blanches', 'Armes blanches'), ('Explosifs', 'Explosifs'), ('Armes improvisées', 'Armes improvisées')], max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('modificateur', models.CharField(max_length=50)),
                ('dommage', models.CharField(max_length=5)),
                ('portee', models.CharField(choices=[('Armes à Feu', 'Arme à Feu'), ('Armes blanches', 'Armes blanches'), ('Explosifs', 'Explosifs'), ('Armes improvisées', 'Armes improvisées')], max_length=20)),
                ('cadence', models.CharField(default='nombre de tir par round à definir', max_length=50)),
                ('munition', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Arme à Feu',
                'verbose_name_plural': 'Armes à Feu',
            },
        ),
    ]
