# Generated by Django 4.2 on 2023-05-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cthulhu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigateur',
            name='blessure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigateur',
            name='histoire_perso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigateur',
            name='niveau_vie',
            field=models.CharField(blank=True, choices=[('Riche (95%)', 'Riche (95%)'), ('Pauvre (25%)', 'Pauvre (25%)'), ('Classe moyenne (50%)', 'Classe moyenne (50%)'), ('Indigent (5%)', 'Indigent (5%)'), ('Aisée (75%)', 'Aisée (75%)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investigateur',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigateur',
            name='protection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='armes',
            name='portee',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Courte', 'Courte'), ('Proche', 'Proche'), ('Longue', 'Longue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='armes',
            name='type',
            field=models.CharField(choices=[('Armes blanches', 'Armes blanches'), ('Armes à Feu', 'Arme à Feu'), ('Armes improvisées', 'Armes improvisées'), ('Explosifs', 'Explosifs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='campagnecthulhu',
            name='style_de_jeu',
            field=models.CharField(choices=[('Investigation Occulte', 'Investigation Occulte'), ('Aventure Pulp', 'Aventure Pulp'), ('Horreur Lovecraftienne', 'Horreur Lovecraftienne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='competenceinvestigateur',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Sensorielle', 'Sensorielle'), ('Connaissance', 'Connaissance'), ('Influence', 'Influence'), ('Savoir-faire', 'Savoir-faire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='investigateur',
            name='etat_investigateur',
            field=models.CharField(choices=[('Avec Cthulhu', 'Avec Cthulhu'), ('Actif', 'Actif'), ('En pause', 'En pause'), ('Fou', 'Fou'), ('Mort', 'Mort')], max_length=20),
        ),
        migrations.AlterField(
            model_name='investigateur',
            name='occupation',
            field=models.CharField(choices=[('Médecin', 'Médecin'), ('Détective', 'Détective'), ('Homme de foi', 'Homme de foi'), ('Dilettante', 'Dilettante'), ('Militaire', 'Militaire'), ('Universitaire', 'Universitaire'), ('Explorateur', 'Explorateur'), ('Artiste', 'Artiste'), ('Baroudeur', 'Baroudeur'), ('Journaliste', 'Journaliste')], max_length=50),
        ),
        migrations.AlterField(
            model_name='investigateur',
            name='personnalite',
            field=models.CharField(choices=[('Anxieux', 'Anxieux'), ('Timide', 'Timide'), ('Méfiant', 'Méfiant'), ('Tatillon', 'Tatillon'), ('Jovial', 'Jovial'), ('Flegmatique', 'Flegmatique'), ('Taciturne', 'Taciturne'), ('Sanguin', 'Sanguin'), ('Narcissique', 'Narcissique'), ('Obsessionnel', 'Obsessionnel')], max_length=50),
        ),
        migrations.CreateModel(
            name='SequellePsycologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('effet', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Sequelle Psycologique',
                'verbose_name_plural': 'Sequelles Psycologiques',
            },
        ),
        migrations.CreateModel(
            name='SequellePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Sequelle Physique',
                'verbose_name_plural': 'Sequelles Physiques',
            },
        ),
        migrations.CreateModel(
            name='SavoirImpie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Créatures connues', 'Créatures connues'), ('Ouvrages consultés', 'Ouvrages consultés')], max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Savoir Impie',
                'verbose_name_plural': 'Savoirs Impies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('attitude', models.CharField(max_length=50)),
                ('circonstance', models.CharField(max_length=50)),
                ('scenario', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('investigateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cthulhu.investigateur')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
