competences_par_categories = {
    "Connaissance": {
        "Bureaucratie": "10%",
        "Culture Artistique*": "10%",
        "Langue Maternelle*": "00%",
        "Langues*": "00%",
        "Mythe de Cthulhu": "00%",
        "Sciences de la terre*": "00%",
        "Sciences de la vie*": "00%",
        "Sciences formelles*": "00%",
        "Sciences humaines*": "00%",
        "Sciences occultes": "05%",
    },
    "Savoir-faire": {
        "Bricolage": "20%",
        "Criminalistique": "00%",
        "Hypnose": "05%",
        "Médecine": "05%",
        "Métier*": "05%",
        "Photographie": "10%",
        "Pratique Artistique*": "10%",
        "Premiers Soins": "30%",
        "Psychanalyse": "00%",
        "Survie": "20%",
    },
    "Sensorielle": {
        "Bibliothèque": "25%",
        "Discrétion": "10%",
        "Dissimulation": "15%",
        "Ecouter": "25%",
        "Orientation": "10%",
        "Pister": "10%",
        "Psychologie": "05%",
        "Se Cacher": "10%",
        "Trouver Objet Caché": "25%",
        "Vigilance": "25%",
    },
    "Influence": {
        "Baratin": "05%",
        "Contacts & Ressources": "10%",
        "Crédit": "15%",
        "Imposture": "00%",
        "Interroger": "10%",
        "Jeu*": "10%",
        "Négociation": "05%",
        "Perspicacité": "00%",
        "Persuasion": "15%",
        "Savoir-vivre": "00%",
    },
    "Action": {
        "Armes à Feu*": "20%",
        "Armes blanches*": "20%",
        "Armes exotiques*": "00%",
        "Artillerie*": "15%",
        "Athlétisme": "15%",
        "Conduite*": "20%",
        "Corps à corps*": "00%",
        "Equitation": "05%",
        "Navigation": "00%",
        "Piloter*": "00%",
    },
}
